export const routes = {
  ROOT: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  EMAIL_VERIFY: '/email/:verify',
  PASSWORD: '/password',
  DOCS: '/docs',
  VALIDATE: '/validate',
  BINANCE: '/binance',
  BITMEX_STRATEGY: '/strategies/bitmex/:pair',
  PORTFOLIO: '/portfolio',
  STRATEGIES: '/strategies',
  FUNDS: '/funds',
  SANDBOX: '/sandbox',
};
