// USER REDUCER ACTIONS
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const UPDATE_USER = 'UPDATE_USER';

// SETTINGS REDUCER ACTIONS
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const SET_LOADING = 'SET_LOADING';

// STRATEGIES REDUCER ACTIONS
export const SET_STRATEGIES = 'SET_STRATEGIES';
export const CLEAR_STRATEGIES = 'CLEAR_STRATEGIES';

// STRATEGY REDUCER ACTIONS
export const SET_STRATEGY = 'SET_STRATEGY';
export const CLEAR_STRATEGY = 'CLEAR_STRATEGY';

// WALLET REDUCER ACTIONS
export const SET_WALLET = 'SET_WALLET';
export const CLEAR_WALLET = 'CLEAR_WALLET';

// FUNDING REDUCER ACTIONS
export const SET_FUNDING = 'SET_FUNDING';
export const CLEAR_FUNDING = 'CLEAR_FUNDING';
